#ifndef SERVER_VOICE_PROTOCOL_H
#define SERVER_VOICE_PROTOCOL_H

#ifdef __cplusplus
extern "C" {
#endif

#include "esp111_protocol_common.h"

/* 语音 turn 协议参数：C5 只上传到 ESPS3 local gateway，由 S3 转发云端。 */
#ifndef SERVER_VOICE_TURN_ENDPOINT
#define SERVER_VOICE_TURN_ENDPOINT ESP111_PROTOCOL_ROUTE_VOICE_TURN
#endif

#ifndef SERVER_VOICE_REQUEST_CONTENT_TYPE
#define SERVER_VOICE_REQUEST_CONTENT_TYPE ESP111_PROTOCOL_AUDIO_CONTENT_TYPE_L16_16K_MONO
#endif

#ifndef SERVER_VOICE_RESPONSE_CONTENT_TYPE
#define SERVER_VOICE_RESPONSE_CONTENT_TYPE ESP111_PROTOCOL_AUDIO_RESPONSE_CONTENT_TYPE
#endif

#ifndef SERVER_VOICE_AUDIO_FORMAT
#define SERVER_VOICE_AUDIO_FORMAT ESP111_PROTOCOL_AUDIO_FORMAT_PCM_S16LE_MONO_16K
#endif

#ifndef SERVER_VOICE_SAMPLE_RATE_HZ
#define SERVER_VOICE_SAMPLE_RATE_HZ 16000 // 上传/返回 PCM 采样率。
#endif

#ifndef SERVER_VOICE_HTTP_CONNECT_TIMEOUT_MS
#define SERVER_VOICE_HTTP_CONNECT_TIMEOUT_MS 30000 // 语音 turn 建连/open/上传阶段超时。
#endif

#ifndef SERVER_VOICE_HTTP_FETCH_HEADERS_TIMEOUT_MS
#define SERVER_VOICE_HTTP_FETCH_HEADERS_TIMEOUT_MS 30000 // 上传完成后等待 S3 响应头。
#endif

#ifndef VOICE_READ_TIMEOUT_MS
#define VOICE_READ_TIMEOUT_MS 15000 // 语音响应 PCM 单次 read 上限。
#endif

#ifndef SERVER_VOICE_HTTP_READ_TIMEOUT_MS
#define SERVER_VOICE_HTTP_READ_TIMEOUT_MS VOICE_READ_TIMEOUT_MS
#endif

#ifndef VOICE_TOTAL_TIMEOUT_MS
#define VOICE_TOTAL_TIMEOUT_MS 90000 // 整个语音 turn 总上限。
#endif

#ifndef SERVER_VOICE_HTTP_TURN_TIMEOUT_MS
#define SERVER_VOICE_HTTP_TURN_TIMEOUT_MS VOICE_TOTAL_TIMEOUT_MS
#endif

#ifndef SERVER_VOICE_HTTP_TIMEOUT_MS
#define SERVER_VOICE_HTTP_TIMEOUT_MS SERVER_VOICE_HTTP_TURN_TIMEOUT_MS
#endif

#ifdef __cplusplus
}
#endif

#endif /* SERVER_VOICE_PROTOCOL_H */
