#include "environment_alarm_engine_internal.h"

#include <math.h>

static bool in_range(float v,float lo,float hi) { return isfinite(v)&&v>=lo&&v<=hi; }
static bool temp_ok(const alarm_environment_sample_t*s){return in_range(s->temperature,-40,85);} static bool humidity_ok(const alarm_environment_sample_t*s){return in_range(s->humidity,0,100);} static bool score_ok(const alarm_environment_sample_t*s){return in_range(s->air_quality_score,0,100);} static bool ratio_ok(const alarm_environment_sample_t*s){return in_range(s->gas_ratio,.000001f,10);} static bool stability_ok(const alarm_environment_sample_t*s){return in_range(s->stability_score,0,1);}
static bool state_ok(const alarm_environment_sample_t*s){return s->sensor_state==ALARM_SENSOR_WARMUP||s->sensor_state==ALARM_SENSOR_READY||s->sensor_state==ALARM_SENSOR_DEGRADED;}
static bool aq_ok(const alarm_environment_sample_t*s){return s->sensor_state==ALARM_SENSOR_READY&&score_ok(s)&&s->air_quality_level>=ALARM_AIR_QUALITY_EXCELLENT&&s->air_quality_level<ALARM_AIR_QUALITY_UNKNOWN;}
static bool ready_score_ok(const alarm_environment_sample_t*s){return s->sensor_state==ALARM_SENSOR_READY&&score_ok(s);}
static void pending_clear(alarm_rule_runtime_t*r){r->state=ALARM_RULE_NORMAL;r->pending_since_ms=0;r->pending_sample_count=0;} static void recovery_clear(alarm_rule_runtime_t*r){r->recovery_since_ms=0;r->recovery_sample_count=0;}
static uint64_t alarm_id(const alarm_device_runtime_t*d,alarm_type_t t,uint32_t cycle){return (g_alarm_engine.boot_nonce<<16U)^((uint64_t)d->device_id<<12U)^((uint64_t)t<<32U)^cycle;}
static void activate(alarm_device_runtime_t*d,alarm_type_t t,alarm_rule_runtime_t*r,const alarm_environment_sample_t*s,alarm_level_t level,uint64_t now,alarm_reason_t reason){r->state=ALARM_RULE_ACTIVE;recovery_clear(r);r->cycle_seq++;r->alarm_id=alarm_id(d,t,r->cycle_seq);r->activated_at_ms=now;r->level=level;alarm_events_emit(s,r,t,level,ALARM_STATUS_ACTIVE,reason,false,ALARM_LEVEL_WARNING,0,r->participant_conditions,now);}
static void recover(alarm_rule_runtime_t*r,const alarm_environment_sample_t*s,alarm_type_t t,uint64_t now,alarm_reason_t reason){alarm_events_emit(s,r,t,r->level,ALARM_STATUS_RECOVERED,reason,false,ALARM_LEVEL_WARNING,0,r->participant_conditions,now);r->state=ALARM_RULE_NORMAL;recovery_clear(r);r->alarm_id=0;r->activated_at_ms=0;r->participant_conditions=0;}
static bool standard(alarm_device_runtime_t*d,alarm_type_t t,alarm_rule_runtime_t*r,const alarm_environment_sample_t*s,bool valid,bool trigger,bool recovery,uint32_t trigger_ms,uint16_t trigger_samples,uint32_t recovery_ms,uint16_t recovery_samples,alarm_level_t level,uint64_t now,alarm_reason_t active_reason,alarm_reason_t recovery_reason){
    bool activated=false;
    const bool gap=valid&&r->last_valid_ms&&now-r->last_valid_ms>g_alarm_config.max_inter_sample_gap_ms;
    if(r->state==ALARM_RULE_NORMAL){
        if(valid&&trigger){r->state=ALARM_RULE_PENDING;r->pending_since_ms=now;r->pending_sample_count=1;}
    } else if(r->state==ALARM_RULE_PENDING){
        if(!valid||!trigger||gap){
            pending_clear(r);
        } else {
            if(r->pending_sample_count<UINT16_MAX)++r->pending_sample_count;
            if(now-r->pending_since_ms>=trigger_ms&&r->pending_sample_count>=trigger_samples){activate(d,t,r,s,level,now,active_reason);activated=true;}
        }
    } else if(!valid||gap){
        recovery_clear(r);
    } else if(trigger){
        recovery_clear(r);
    } else if(recovery){
        if(!r->recovery_sample_count)r->recovery_since_ms=now;
        if(r->recovery_sample_count<UINT16_MAX)++r->recovery_sample_count;
        if(now-r->recovery_since_ms>=recovery_ms&&r->recovery_sample_count>=recovery_samples)recover(r,s,t,now,recovery_reason);
    } else {
        recovery_clear(r);
    }
    if(valid)r->last_valid_ms=now;
    return activated;
}
static float delta(const alarm_history_t*h,bool*ok){float old;if(!alarm_history_oldest(h,&old)){*ok=false;return 0;}*ok=true;const uint16_t i=(uint16_t)((h->head+h->count-1U)%h->capacity);return fabsf(h->items[i].value-old);}
static void temperature(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){bool cv;float c=delta(&d->temperature_history,&cv);standard(d,ALARM_TYPE_HIGH_TEMPERATURE,&d->rules[ALARM_TYPE_HIGH_TEMPERATURE],s,temp_ok(s),temp_ok(s)&&s->temperature>=g_alarm_config.high_temperature_trigger,temp_ok(s)&&s->temperature<=g_alarm_config.high_temperature_recovery,g_alarm_config.trigger_60s_ms,3,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);standard(d,ALARM_TYPE_LOW_TEMPERATURE,&d->rules[ALARM_TYPE_LOW_TEMPERATURE],s,temp_ok(s),temp_ok(s)&&s->temperature<=g_alarm_config.low_temperature_trigger,temp_ok(s)&&s->temperature>=g_alarm_config.low_temperature_recovery,g_alarm_config.trigger_60s_ms,3,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);standard(d,ALARM_TYPE_FAST_TEMPERATURE_CHANGE,&d->rules[ALARM_TYPE_FAST_TEMPERATURE_CHANGE],s,cv,cv&&c>=g_alarm_config.fast_temperature_trigger,cv&&c<=g_alarm_config.fast_temperature_recovery,0,2,g_alarm_config.recovery_120s_ms,1,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);}
static void humidity(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){bool cv;float c=delta(&d->humidity_history,&cv);standard(d,ALARM_TYPE_HIGH_HUMIDITY,&d->rules[ALARM_TYPE_HIGH_HUMIDITY],s,humidity_ok(s),humidity_ok(s)&&s->humidity>=g_alarm_config.high_humidity_trigger,humidity_ok(s)&&s->humidity<=g_alarm_config.high_humidity_recovery,g_alarm_config.trigger_60s_ms,3,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);standard(d,ALARM_TYPE_LOW_HUMIDITY,&d->rules[ALARM_TYPE_LOW_HUMIDITY],s,humidity_ok(s),humidity_ok(s)&&s->humidity<=g_alarm_config.low_humidity_trigger,humidity_ok(s)&&s->humidity>=g_alarm_config.low_humidity_recovery,g_alarm_config.trigger_60s_ms,3,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);standard(d,ALARM_TYPE_FAST_HUMIDITY_CHANGE,&d->rules[ALARM_TYPE_FAST_HUMIDITY_CHANGE],s,cv,cv&&c>=g_alarm_config.fast_humidity_trigger,cv&&c<=g_alarm_config.fast_humidity_recovery,0,2,g_alarm_config.recovery_120s_ms,1,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);}
static void sensor_degraded(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){standard(d,ALARM_TYPE_SENSOR_DEGRADED,&d->rules[ALARM_TYPE_SENSOR_DEGRADED],s,state_ok(s),s->sensor_state==ALARM_SENSOR_DEGRADED,s->sensor_state==ALARM_SENSOR_READY,0,3,0,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);}
static bool aq_critical_trigger(const alarm_environment_sample_t*s){return aq_ok(s)&&(s->air_quality_score<=g_alarm_config.aq_critical_trigger||s->air_quality_level==ALARM_AIR_QUALITY_BAD);} static bool aq_critical_recover(const alarm_environment_sample_t*s){return aq_ok(s)&&s->air_quality_score>=g_alarm_config.aq_critical_recovery&&s->air_quality_level!=ALARM_AIR_QUALITY_BAD;} static bool aq_warning_trigger(const alarm_environment_sample_t*s){return aq_ok(s)&&(s->air_quality_score<=g_alarm_config.aq_warning_trigger||s->air_quality_level==ALARM_AIR_QUALITY_POOR);} static bool aq_warning_recover(const alarm_environment_sample_t*s){return aq_ok(s)&&s->air_quality_score>=g_alarm_config.aq_warning_recovery&&s->air_quality_level!=ALARM_AIR_QUALITY_POOR&&s->air_quality_level!=ALARM_AIR_QUALITY_BAD;}
static void air_quality(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){alarm_rule_runtime_t*w=&d->rules[ALARM_TYPE_AIR_QUALITY_WARNING],*c=&d->rules[ALARM_TYPE_AIR_QUALITY_CRITICAL];bool was=c->state==ALARM_RULE_ACTIVE;bool activated=standard(d,ALARM_TYPE_AIR_QUALITY_CRITICAL,c,s,aq_ok(s),aq_critical_trigger(s),aq_critical_recover(s),g_alarm_config.trigger_30s_ms,2,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_CRITICAL,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);bool recovered=was&&c->state==ALARM_RULE_NORMAL;if(activated&&w->state==ALARM_RULE_ACTIVE){alarm_events_emit(s,w,ALARM_TYPE_AIR_QUALITY_WARNING,w->level,ALARM_STATUS_RECOVERED,ALARM_REASON_ESCALATED_TO_CRITICAL,false,ALARM_LEVEL_WARNING,0,0,n);alarm_events_swap_last_two();pending_clear(w);recovery_clear(w);w->alarm_id=0;w->activated_at_ms=0;}if(c->state==ALARM_RULE_ACTIVE||c->state==ALARM_RULE_PENDING||recovered){if(w->state==ALARM_RULE_PENDING)pending_clear(w);return;}standard(d,ALARM_TYPE_AIR_QUALITY_WARNING,w,s,aq_ok(s),aq_warning_trigger(s),aq_warning_recover(s),g_alarm_config.trigger_60s_ms,3,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);}
static void deteriorating(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){alarm_rule_runtime_t*r=&d->rules[ALARM_TYPE_AIR_QUALITY_DETERIORATING];float max;bool valid=ready_score_ok(s)&&ratio_ok(s)&&alarm_history_max(&d->air_quality_history,&max);bool trig=valid&&max-s->air_quality_score>=g_alarm_config.aq_deteriorating_delta&&s->air_quality_score<70&&s->gas_ratio<=g_alarm_config.aq_deteriorating_gas_ratio_max;bool rec=r->state==ALARM_RULE_ACTIVE&&valid&&(s->air_quality_score-r->activation_score>=10||s->air_quality_score>=70);if(rec)trig=false;if(standard(d,ALARM_TYPE_AIR_QUALITY_DETERIORATING,r,s,valid,trig,rec,g_alarm_config.trigger_60s_ms,1,g_alarm_config.recovery_10min_ms,1,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED))r->activation_score=s->air_quality_score;}
static void pollution(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){alarm_rule_runtime_t*r=&d->rules[ALARM_TYPE_POLLUTION_SPIKE];bool valid=s->sensor_state==ALARM_SENSOR_READY&&ratio_ok(s);bool activated=standard(d,ALARM_TYPE_POLLUTION_SPIKE,r,s,valid,valid&&s->gas_ratio<=.70f,valid&&s->gas_ratio>=.80f,0,2,g_alarm_config.recovery_120s_ms,3,valid&&s->gas_ratio<=.55f?ALARM_LEVEL_CRITICAL:ALARM_LEVEL_HIGH,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);(void)activated;if(r->state==ALARM_RULE_ACTIVE&&r->level==ALARM_LEVEL_HIGH&&valid&&s->gas_ratio<=.55f){if(r->escalation_sample_count<2)++r->escalation_sample_count;if(r->escalation_sample_count==2){r->level=ALARM_LEVEL_CRITICAL;alarm_events_emit(s,r,ALARM_TYPE_POLLUTION_SPIKE,ALARM_LEVEL_CRITICAL,ALARM_STATUS_ACTIVE,ALARM_REASON_LEVEL_ESCALATED,true,ALARM_LEVEL_HIGH,0,0,n);r->escalation_sample_count=UINT16_MAX;}}else if(r->state!=ALARM_RULE_ACTIVE||(r->level==ALARM_LEVEL_HIGH&&(!valid||s->gas_ratio>.55f)))r->escalation_sample_count=0;}
static void unstable(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){bool v=s->sensor_state==ALARM_SENSOR_READY&&stability_ok(s);standard(d,ALARM_TYPE_ENVIRONMENT_UNSTABLE,&d->rules[ALARM_TYPE_ENVIRONMENT_UNSTABLE],s,v,v&&s->stability_score<.55f,v&&s->stability_score>=.70f,0,3,g_alarm_config.recovery_120s_ms,3,ALARM_LEVEL_WARNING,n,ALARM_REASON_THRESHOLD_CONFIRMED,ALARM_REASON_RECOVERY_CONFIRMED);}
static uint32_t conditions(const alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint32_t*available){uint32_t c=0;*available=0;if(s->sensor_state!=ALARM_SENSOR_READY)return 0;if(temp_ok(s)){*available|=3;if(d->rules[ALARM_TYPE_AIR_QUALITY_CRITICAL].state==ALARM_RULE_ACTIVE&&d->rules[ALARM_TYPE_HIGH_TEMPERATURE].state==ALARM_RULE_ACTIVE&&s->temperature>=40)c|=1;if(d->rules[ALARM_TYPE_AIR_QUALITY_CRITICAL].state==ALARM_RULE_ACTIVE&&d->rules[ALARM_TYPE_LOW_TEMPERATURE].state==ALARM_RULE_ACTIVE&&s->temperature<=5)c|=2;}if(humidity_ok(s)){*available|=12;if(d->rules[ALARM_TYPE_POLLUTION_SPIKE].state==ALARM_RULE_ACTIVE&&d->rules[ALARM_TYPE_HIGH_HUMIDITY].state==ALARM_RULE_ACTIVE&&s->humidity>=85)c|=4;if(d->rules[ALARM_TYPE_POLLUTION_SPIKE].state==ALARM_RULE_ACTIVE&&d->rules[ALARM_TYPE_LOW_HUMIDITY].state==ALARM_RULE_ACTIVE&&s->humidity<=15)c|=8;}return c;}
static void composite(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){alarm_rule_runtime_t*r=&d->rules[ALARM_TYPE_CRITICAL_ENVIRONMENT];uint32_t avail,cond=conditions(d,s,&avail);bool eval_active=r->state==ALARM_RULE_ACTIVE&&r->participant_conditions&&((avail&r->participant_conditions)==r->participant_conditions);bool valid=r->state==ALARM_RULE_ACTIVE?eval_active:cond!=0;bool rec=eval_active&&(cond&r->participant_conditions)==0;if(r->state==ALARM_RULE_NORMAL&&cond)r->participant_conditions=cond;else if((r->state==ALARM_RULE_PENDING||r->state==ALARM_RULE_ACTIVE)&&cond)r->participant_conditions|=cond;standard(d,ALARM_TYPE_CRITICAL_ENVIRONMENT,r,s,valid,cond!=0,rec,g_alarm_config.combination_trigger_ms,1,g_alarm_config.combination_recovery_ms,1,ALARM_LEVEL_CRITICAL,n,ALARM_REASON_COMBINED_CONDITIONS_CONFIRMED,ALARM_REASON_COMBINED_CONDITIONS_RECOVERED);if(r->state==ALARM_RULE_NORMAL)r->participant_conditions=0;}
void alarm_rules_process(alarm_device_runtime_t*d,const alarm_environment_sample_t*s,uint64_t n){temperature(d,s,n);humidity(d,s,n);sensor_degraded(d,s,n);if(s->sensor_state==ALARM_SENSOR_READY){air_quality(d,s,n);deteriorating(d,s,n);pollution(d,s,n);unstable(d,s,n);}else for(alarm_type_t t=ALARM_TYPE_AIR_QUALITY_WARNING;t<=ALARM_TYPE_ENVIRONMENT_UNSTABLE;t++){alarm_rule_runtime_t*r=&d->rules[t];if(r->state==ALARM_RULE_PENDING)pending_clear(r);else if(r->state==ALARM_RULE_ACTIVE)recovery_clear(r);}composite(d,s,n);}
